#!/bin/bash

#PBS -N polyester
#PBS -q common
#PBS -l nodes=1:ppn=1
#PBS -m bea
#PBS -M haoliang.xue@i2bc.paris-saclay.fr

set -e

tx_fasta="/data/work/I2BC/haoliang.xue/kamrat/paper/b_reference_gen/a_selected_transcripts.fa"
ev_fasta="/data/work/I2BC/haoliang.xue/kamrat/paper/b_reference_gen/c_variation_events.fa"
outdir="/data/work/I2BC/haoliang.xue/kamrat/paper/c_simulated_reads"

# mkdir -p $outdir/a_ref $outdir/b_errfree_10smp $outdir/c_witherr_10smp $outdir/d_witherr_100vs100

# cat $tx_fasta $ev_fasta > $outdir/a_ref/ref4simu.fa

# makeblastdb -in $outdir/a_ref/ref4simu.fa -dbtype nucl -title 3765tx_612var -parse_seqids -out $outdir/a_ref/ref4simu

# /home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/projects/KaMRaT-paper/submodules/c1_simulate_reads.R $outdir/a_ref/ref4simu.fa $outdir/b_errfree_10smp false
# /home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/projects/KaMRaT-paper/submodules/c1_simulate_reads.R $outdir/a_ref/ref4simu.fa $outdir/c_witherr_10smp true
/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/projects/KaMRaT-paper/submodules/c2_simulate_reads_from_mat.R $outdir/a_ref/ref4simu.fa $outdir/d_witherr_100vs100
