#!/bin/bash

#PBS -N SPAdes
#PBS -q common
#PBS -l nodes=1:ppn=10
#PBS -M haoliang.xue@i2bc.paris-saclay.fr
#PBS -m bea

set -e

errfree_read_dir="/data/work/I2BC/haoliang.xue/kamrat/paper/c_simulated_reads/b_errfree_10smp"
witherr_read_dir="/data/work/I2BC/haoliang.xue/kamrat/paper/c_simulated_reads/c_witherr_10smp"
out_dir="/data/work/I2BC/haoliang.xue/kamrat/paper/d_SPAdes_res"
blastdb_name="/data/work/I2BC/haoliang.xue/kamrat/paper/c_simulated_reads/a_ref/ref4simu"

# bash /store/USERS/haoliang.xue/projects/KaMRaT-paper/submodules/d1_SPAdes_align.bash $errfree_read_dir $out_dir/a_errfree $blastdb_name
# bash /store/USERS/haoliang.xue/projects/KaMRaT-paper/submodules/d1_SPAdes_align.bash $witherr_read_dir $out_dir/b_witherr $blastdb_name

bash /store/USERS/haoliang.xue/projects/KaMRaT-paper/submodules/d2_SPAdes_align_allsmp.bash $errfree_read_dir $out_dir/a_errfree $blastdb_name
bash /store/USERS/haoliang.xue/projects/KaMRaT-paper/submodules/d2_SPAdes_align_allsmp.bash $witherr_read_dir $out_dir/b_witherr $blastdb_name
