#!/bin/bash

#PBS -N KaMRaT_merge_align
#PBS -q ssfa
#PBS -l nodes=1:ppn=10
#PBS -M haoliang.xue@i2bc.paris-saclay.fr
#PBS -m ea

set -e

in_tab_dir="/data/work/I2BC/haoliang.xue/kamrat/paper/simulation/e_jellyfish_joinCount_res"
blastdb_name="/data/work/I2BC/haoliang.xue/kamrat/paper/simulation/c_simulated_reads/a_ref/ref4simu"
out_dir="/data/work/I2BC/haoliang.xue/kamrat/paper/simulation/f_kamrat_res"

# error-free #
mkdir -p $out_dir/a_randsel/errfree $out_dir/a_randsel/witherr
for r in $(seq 10 10 100)
do
	for interv_method in $(echo "none mac:0.32 pearson:0.21 spearman:0.23")
	do
		/store/USERS/haoliang.xue/development/KaMRaT/paper-code/simulation/submodules/f1_kamrat_merge_align.bash $in_tab_dir/a_errfree/31/raw-counts-$r"pct"-1-1.tsv $out_dir/a_randsel/errfree/merged $interv_method $blastdb_name 31
		/store/USERS/haoliang.xue/development/KaMRaT/paper-code/simulation/submodules/f1_kamrat_merge_align.bash $in_tab_dir/b_witherr/31/raw-counts-$r"pct"-1-3.tsv $out_dir/a_randsel/witherr/merged $interv_method $blastdb_name 31
	done
done

#for k in $(echo 31 25 21 19 15)
#do
#	for m in $(seq $((k-1)) -1 $((k/2)))
#	do
#		mkdir -p $out_dir/b_errfree_interval/$k-$m
#
#		for interv_method in $(echo "none mac:0.32 pearson:0.21 spearman:0.23")
#		do
#			/store/USERS/haoliang.xue/development/KaMRaT/paper-code/simulation/submodules/f1_kamrat_merge_align.bash $in_tab_dir/a_errfree/$k/raw-counts-100pct-1-1.tsv $out_dir/b_errfree_interval/$k-$m/merged $interv_method $blastdb_name $k $m
#		done	
#	done
#done
#
#mkdir -p $out_dir/c_witherr_filter
#for f in $in_tab_dir/b_witherr/31/raw-counts-100pct-*.tsv
#do 
#	for interv_method in $(echo "none mac:0.32 pearson:0.21 spearman:0.23")
#	do
#		/store/USERS/haoliang.xue/development/KaMRaT/paper-code/simulation/submodules/f1_kamrat_merge_align.bash $f $out_dir/c_witherr_filter/merged $interv_method $blastdb_name 31
#	done
#done
