#!/bin/bash

#PBS -N exten_assemb_cmp
#PBS -m ea
#PBS -M haoliang.xue@i2bc.paris-saclay.fr
#PBS -q ssfa

kamrat_res_dir="/data/work/I2BC/haoliang.xue/kamrat/paper/simulation/f_kamrat_res"
spades_res_dir="/data/work/I2BC/haoliang.xue/kamrat/paper/simulation/d_SPAdes_res"
kmer_tab_dir="/data/work/I2BC/haoliang.xue/kamrat/paper/simulation/e_jellyfish_joinCount_res"
out_dir="/data/work/I2BC/haoliang.xue/kamrat/paper/simulation/g_KaMRaT_merge_eval"

set -e

mkdir -p $out_dir

/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/development/KaMRaT/paper-code/simulation/submodules/g1_local_global_comparison.R $kamrat_res_dir/a_errfree_randsel/merged-contigs-align-100pct-1-1. $spades_res_dir/a_errfree $out_dir

/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/development/KaMRaT/paper-code/simulation/submodules/g2_wrong_extension_comparison.R $spades_res_dir/a_errfree $kmer_tab_dir/a_errfree/31/raw-counts- $kamrat_res_dir $out_dir
wc -l $kmer_tab_dir/a_errfree/*/raw-counts-100pct-1-1.tsv | awk '$2 != "total" {split($2, a, "/"); print "k="a[10]": "$1}' > $out_dir/kmer_count.summary.txt

/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/development/KaMRaT/paper-code/simulation/submodules/g3_N50_comparison.R $kamrat_res_dir $spades_res_dir $out_dir
