#!/bin/bash

#PBS -N kM
#PBS -l nodes=1:ppn=1
#PBS -q common
#PBS -m ea
#PBS -M haoliang.xue@i2bc.paris-saclay.fr

set -e

tab_dir="/store/EQUIPES/SSFA/MEMBERS/haoliang.xue/kamrat-paper/prad-tcga/b_splitCV"
out_prefix="/data/work/I2BC/haoliang.xue/PRAD_TCGA_risk/c_kamratRes/c2_rank-first/train"

nb_fold=5

for i in $(seq 0 $((nb_fold - 1)))
do
	smp_condi=$tab_dir"/sampleshuf.train"$i".tsv"

	method_list=(ttest snr lrc nbc)
	method_suffix=(.padj "" .f1 .f1 .hingeloss)
	method_sort=(min maxabs max max)
	for j in $(seq 0 3) 
	do
		m=${method_list[$j]}
		out_dir=$out_prefix$i/$m
		score_method=$m${method_suffix[$j]}:${method_sort[$j]}

		head -n 100001 $out_dir/ranked-kmer-counts.tsv > $out_dir/top100000-kmer-counts.tsv
		/store/USERS/haoliang.xue/development/KaMRaT/bin/kamrat merge -klen 31 -idx-path $out_dir/merge.idx -unstrand -smp-info <(sed '1d' $smp_condi) -interv-method mac:0.32 -quant-mode mean -rep-name $score_method -out-path $out_dir/contig-counts.tsv $out_dir/top100000-kmer-counts.tsv
	        rm -f $out_dir/merge.idx
		sed -i "s/$m${method_suffix[$j]}/score/g" $out_dir/contig-counts.tsv
	done
done
