#!/bin/bash

#PBS -N models_assessG
#PBS -q ssfa
#PBS -m ea
#PBS -M haoliang.xue@i2bc.paris-saclay.fr

set -e

proj_dir="/data/work/I2BC/haoliang.xue/PRAD_TCGA"
mdl_dir=$proj_dir"/e_gene_level/b_rank_res"
out_dir=$proj_dir"/e_gene_level/c_assess_res"

for n in $(seq 0 4)
do
	trained_mdl_path=$mdl_dir/train$n-snr/fitted-model-ridge.rds
	test_count_path=$mdl_dir/train$n-snr/signatures-in-test-ridge.tsv
	smp_info_path=$proj_dir/b_splitCV/sampleshuf.test$n.tsv
	/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/development/KaMRaT/related-tools/downstream_analysis/evaluateModel.R $trained_mdl_path $test_count_path $smp_info_path >> $out_dir/assess_results_rankmethods_ridge.tsv
done
