#!/bin/bash

#PBS -N rsk-fitModel
#PBS -m ea
#PBS -M haoliang.xue@i2bc.paris-saclay.fr
#PBS -q ssfa
#PBS -l nodes=1:ppn=4

set -e

smp_dir="/store/EQUIPES/SSFA/MEMBERS/haoliang.xue/PRAD_TCGA/CVMatrices/risk-new"
dir_prefix="/store/EQUIPES/SSFA/MEMBERS/haoliang.xue/PRAD_TCGA/merging-first/risk-new/train"

for i in $(seq 0 4)
do
	for m in `echo ttest snr lrc nbc`
	do
		out_dir=$dir_prefix$i/$m

		head -n5001 $out_dir/ranked-counts.tsv > $out_dir/top5000-contig-counts.tsv
		/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/development/KaMRaT/related-tools/downstream_analysis/fitModel.R $out_dir/top5000-contig-counts.tsv $smp_dir/sampleshuf.train$i.tsv $out_dir ridge $out_dir/smp-nf.tsv
	done
done

