#!/bin/bash

set -e

dir_prefix="/data/work/I2BC/haoliang.xue/PRAD_TCGA"
out_prefix="/data/work/I2BC/haoliang.xue/PRAD_TCGA/d_signatures/d4_rank-methods"

tab_dir=$dir_prefix"/b_splitCV"
merged_res_dir=$dir_prefix"/c_kamratRes/c3_rank-methods"

node_list=(node22 node06 node15 node23 node27)
for i in $(seq 0 4)
do
	sed "s|\$1|$tab_dir/kmer-counts.test$i.tsv.gz|g; s|\$2|$tab_dir/sampleshuf.test$i.tsv|g; s|\$3|$out_prefix/model.train$i|g" /store/USERS/haoliang.xue/development/KaMRaT/paper-code/prad-tcga/c_kamrat/c3_rank_method/c1_count_test.bytrain.qsub | qsub -N countTest-$i -l nodes=${node_list[$i]}:ppn=1
done

