#!/bin/bash

#PBS -N selSigs
#PBS -q ssfa
#PBS -m ea
#PBS -M haoliang.xue@i2bc.paris-saclay.fr

set -e

smp_dir="/store/EQUIPES/SSFA/MEMBERS/haoliang.xue/kamrat-paper/prad-tcga-relapse/b_splitCV"

dir_prefix="/data/work/I2BC/haoliang.xue/PRAD_TCGA_relapse/f_gene/b_rank_res/train"

for i in $(seq 0 4)
do
	smp_info=$smp_dir/sampleshuf.train$i.tsv
	
	method_list=(ttest snr lrc nbc svm)
	for m in ${method_list[@]} 
	do
		out_dir=$dir_prefix$i/$m

		head -n 5001 $out_dir/ranked-gene-counts.tsv > $out_dir/top5000-gene-counts.tsv
				
		/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/development/KaMRaT/related-tools/downstream_analysis/fitModel.R $out_dir/top5000-gene-counts.tsv $smp_info $out_dir lasso $out_dir/smp-nf.tsv
		/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/development/KaMRaT/related-tools/downstream_analysis/fitModel.R $out_dir/top5000-gene-counts.tsv $smp_info $out_dir ridge $out_dir/smp-nf.tsv
	done
done

