#!/bin/bash

#PBS -N countSigInTest
#PBS -m ea
#PBS -M haoliang.xue@i2bc-paris-saclay.fr

set -e

dir_prefix="/data/work/I2BC/haoliang.xue/PRAD_TCGA_relapse/f_gene"

for i in $(seq 0 4)
do
	method_list=(ttest snr lrc nbc svm)
	for m in ${method_list[@]} 
	do
		count_tab=$dir_prefix/a_count-matrices/gene-counts.test$i.tsv
		out_dir=$dir_prefix/b_rank_res/train$i/$m
		/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/development/KaMRaT/related-tools/downstream_analysis/selGeneFromMat.R $out_dir/signatures-lasso.fa $count_tab $out_dir/gene-counts-lasso.test.tsv
		/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/development/KaMRaT/related-tools/downstream_analysis/selGeneFromMat.R $out_dir/signatures-ridge.fa $count_tab $out_dir/gene-counts-ridge.test.tsv
	done
done

