#!/bin/bash

#PBS -N rsk-predict
#PBS -m ea
#PBS -M haoliang.xue@i2bc.paris-saclay.fr
#PBS -q common

tab_dir="/store/EQUIPES/SSFA/MEMBERS/haoliang.xue/PRAD_TCGA/CVMatrices/risk-new"
train_prefix="/store/EQUIPES/SSFA/MEMBERS/haoliang.xue/PRAD_TCGA/ranking-first/risk-new/train"
test_prefix="/store/EQUIPES/SSFA/MEMBERS/haoliang.xue/PRAD_TCGA/ranking-first/risk-new/test"

assess_res="/store/EQUIPES/SSFA/MEMBERS/haoliang.xue/PRAD_TCGA/ranking-first/risk-new/assess.all.tsv"

echo -e "metrics\tmodel_path\tvalue" > $assess_res

for i in $(seq 0 4)
do
	test_smp_info=$tab_dir/sampleshuf.test$i.tsv
	method_list=(ttest snr lrc nbc)
	for m in ${method_list[@]}
	do
		mdl=$train_prefix$i/$m/fitted-model-ridge.rds
		test_tab=$test_prefix$i/contig-counts-ridge.$m.tsv
		out_path=$test_prefix$i/prediction.$m.tsv
		/home/haoliang.xue/.conda/envs/dekupl-hlx/bin/Rscript /store/USERS/haoliang.xue/development/KaMRaT/related-tools/downstream_analysis/predict.R $mdl $test_tab $out_path $test_smp_info >> $assess_res
	done
done

